### PR TITLE
Update CinemachineImpulseListener.md

### PR DESCRIPTION
**Pull request by midopooler**

### CODE REVIEW

**Comment by glabute** [comment]
Thank you for all these corrections!  The Cinemachine team really appreciates it.
Don't be shy to bundle them together into beefier PR's, to save some overhead.
Thanks again!

**Comment by midopooler** [comment]
> Thank you for all these corrections! The Cinemachine team really appreciates it.
> Don't be shy to bundle them together into beefier PR's, to save some overhead.
> Thanks again!

Welcome for the above comment. And yes I'll be bundling up beefier PR's from now onwards. 👍

**Comment by midopooler** [comment]
@glabute It might be inappropriate to ask like this.
I was going through the documentation of unity cloud diagnostics and thought of contributing to the docs. [LINK HERE](https://unitytech.github.io/clouddiagnostics/)
But I cannot find any such repository under unity technologies organisation. 
Is it a private repository? If yes, any way through which I could still contribute to it?

**Comment by glabute** [comment]
You're right, it's not the best place to ask.  Try finding me on Slack.
In any case, I don't have an answer to your question, unfortunately.

**Pull request merged**
